"""Adicionar campos de personalidade, poderes e conexoes

Revision ID: 89a3ab95a5df
Revises: 58a72d142b37
Create Date: 2025-06-06 12:49:16.788127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a3ab95a5df'
down_revision = '58a72d142b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('race',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('mask',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('clan',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('bloodline',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('important_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personalidade', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poderes_habilidades', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conexoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('important_character', schema=None) as batch_op:
        batch_op.drop_column('conexoes')
        batch_op.drop_column('poderes_habilidades')
        batch_op.drop_column('personalidade')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('bloodline',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('clan',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('mask',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('race',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
